name: kuncie_test
description: Kuncie Take Home Test

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^3.2.0
  bloc: ^7.2.1
  cached_network_image: ^3.1.0+1
  dio: ^4.0.1
  equatable: ^2.0.3
  flutter_bloc: ^7.2.1
  line_icons: ^2.0.1
  logger: ^1.1.0
  json_annotation: ^4.4.0
  carousel_slider: ^4.0.0
  audioplayers: ^0.20.1
  cupertino_icons: ^1.0.2
  rive: ^0.7.22
  shimmer: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^3.1.0
  build_runner: ^2.1.5
  json_serializable: ^6.1.1
  retrofit_generator: ^2.2.0
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/sound.riv
